#!/usr/bin/env bash

while true; do
  if systemctl --user list-unit-files duplicity-backup.timer --state=disabled &> /dev/null ; then
    echo 'Disabled'
  elif [ $(systemctl --user show duplicity-backup.service --property=SubState --value) == 'start' ]; then
    echo 'Running'
  elif [ $(systemctl --user show duplicity-backup.service --property=ExecMainStatus --value) -eq 0 ]; then
    echo 'OK'
  else
    echo 'Failed'
  fi

  sleep 5
done
