#!/bin/bash

## Author : Aditya Shakya
## Github : adi1090x
# Custom Rofi Script

BORDER="#1F1F1F"
SEPARATOR="#1F1F1F"
FOREGROUND="#FFFFFF"
BACKGROUND="#1F1F1F"
BACKGROUND_ALT="#252525"
HIGHLIGHT_BACKGROUND="#00897b"
HIGHLIGHT_FOREGROUND="#1F1F1F"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

SDIR="$HOME/.bin/polybar"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'Style :' \
-hide-scrollbar true \
-bw 0 \
-lines 5 \
-line-padding 10 \
-padding 20 \
-width 30 \
-xoffset 68 -yoffset -70 \
-location 7 \
-columns 2 \
-show-icons -icon-theme "Papirus" \
-font "Fantasque Sans Mono 10" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< "♥ amber|♥ blue|♥ blue-grey|♥ brown|♥ cyan|♥ deep-orange|♥ deep-purple|♥ green|♥ grey|♥ indigo|♥ blue-light|♥ green-light|♥ lime|♥ orange|♥ pink|♥ purple|♥ red|♥ teal|♥ yellow|♥ amber-dark|♥ blue-dark|♥ blue-grey-dark|♥ brown-dark|♥ cyan-dark|♥ deep-orange-dark|♥ deep-purple-dark|♥ green-dark|♥ grey-dark|♥ indigo-dark|♥ blue-light-dark|♥ green-light-dark|♥ lime-dark|♥ orange-dark|♥ pink-dark|♥ purple-dark|♥ red-dark|♥ teal-dark|♥ yellow-dark")"
            case "$MENU" in
				## Light Colors
				*amber) $SDIR/colors-light -amber ;;
				*blue) $SDIR/colors-light -blue ;;
				*blue-grey) $SDIR/colors-light -blue-grey ;;
				*brown) $SDIR/colors-light -brown ;;
				*cyan) $SDIR/colors-light -cyan ;;
				*deep-orange) $SDIR/colors-light -deep-orange ;;
				*deep-purple) $SDIR/colors-light -deep-purple ;;
				*green) $SDIR/colors-light -green ;;
				*grey) $SDIR/colors-light -grey ;;
				*indigo) $SDIR/colors-light -indigo ;;
				*blue-light) $SDIR/colors-light -light-blue ;;
				*green-light) $SDIR/colors-light -light-green ;;
				*lime) $SDIR/colors-light -lime ;;
				*orange) $SDIR/colors-light -orange ;;
				*pink) $SDIR/colors-light -pink ;;
				*purple) $SDIR/colors-light -purple ;;
				*red) $SDIR/colors-light -red ;;
				*teal) $SDIR/colors-light -teal ;;
				*yellow) $SDIR/colors-light -yellow ;;
				## Dark Colors
				*amber-dark) $SDIR/colors-dark -amber ;;
				*blue-dark) $SDIR/colors-dark -blue ;;
				*blue-grey-dark) $SDIR/colors-dark -blue-grey ;;
				*brown-dark) $SDIR/colors-dark -brown ;;
				*cyan-dark) $SDIR/colors-dark -cyan ;;
				*deep-orange-dark) $SDIR/colors-dark -deep-orange ;;
				*deep-purple-dark) $SDIR/colors-dark -deep-purple ;;
				*green-dark) $SDIR/colors-dark -green ;;
				*grey-dark) $SDIR/colors-dark -grey ;;
				*indigo-dark) $SDIR/colors-dark -indigo ;;
				*blue-light-dark) $SDIR/colors-dark -light-blue ;;
				*green-light-dark) $SDIR/colors-dark -light-green ;;
				*lime-dark) $SDIR/colors-dark -lime ;;
				*orange-dark) $SDIR/colors-dark -orange ;;
				*pink-dark) $SDIR/colors-dark -pink ;;
				*purple-dark) $SDIR/colors-dark -purple ;;
				*red-dark) $SDIR/colors-dark -red ;;
				*teal-dark) $SDIR/colors-dark -teal ;;
				*yellow-dark) $SDIR/colors-dark -yellow				
            esac
