#!/bin/bash

# Set color scheme
wal --theme base16-harmonic

# Set background image
# hsetroot -solid "#dadee3"
nitrogen --restore

# Terminate already running bar instances
killall -q polybar

# Run compositor
killall -q picom ; picom -b

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
polybar --reload main &

echo "Polybar launched..."
