#!/bin/bash

prime-offload

# Set color scheme
wal --theme base16-dracula

# Reload Xresources
xrdb "$HOME/.Xresources"

# Update configuration file and reload dunst
killall -q dunst ; dunst &

# Restore background image
nitrogen --restore

# Terminate already running bar instances
killall -q polybar
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Start compositor
picom -b --experimental-backends

polybar -q my -c "$HOME/.config/polybar/active/my-config.ini" &
