#!/usr/bin/env bash

prop="/xfce4-power-manager/presentation-mode"

while true; do
  if [ $(xfconf-query -c xfce4-power-manager -p "$prop") = "true" ]; then
    echo "Caffeine On"
  else
    echo "Caffeine Off"
  fi
  sleep 0.5
done
