#!/usr/bin/env bash

prop="/xfce4-power-manager/presentation-mode"

while true; do
  if [ $(xfconf-query -c xfce4-power-manager -p "$prop") = "true" ]; then
    echo ""
  else
    echo ""
  fi
  sleep 0.2
done
