---

- name: Restart systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
