---

# Replace jack package with jack2
- name: Make sure jack package is absent
  community.general.pacman:
    state: absent
    force: true
    name:
      - jack

- name: Install packages
  community.general.pacman:
    state: present
    name:
      - ardour
      - calf
      - carla
      - dbus-python
      - dssi-plugins
      - guitarix
      - jack2
      - kdenlive
      - ladspa-plugins
      - lv2-plugins
      - obs-studio
      - pulseaudio-jack
      - realtime-privileges
      - vst-plugins

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - cadence-claudia
