---

- name: Archlinux-specific setup
  import_tasks: archlinux.yml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: System-wide configuration
  import_tasks: system.yml

- name: 'Configuration for {{ user_name }} user'
  import_tasks: user.yml
