---

- name: Ensure the realtime group exists
  ansible.builtin.group:
    name: realtime
    state: present

- name: Ensure security limits are set
  ansible.builtin.copy:
    src: 'etc/security/limits.d/'
    dest: '/etc/security/limits.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Ensure sysctl overrides are set
  ansible.builtin.copy:
    src: 'etc/sysctl.d/'
    dest: '/etc/sysctl.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Ensure PulseAudio configuration is up to date
  ansible.builtin.copy:
    src: etc/pulse/
    dest: /etc/pulse/
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart PulseAudio
