---

- name: Add security limits file
  become: true
  copy:
    src: 'etc/security/limits.d/'
    dest: '/etc/security/limits.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Add sysctl files
  become: true
  copy:
    src: 'etc/sysctl.d/'
    dest: '/etc/sysctl.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Make sure the realtime group exists
  become: true
  group:
    name: realtime
    state: present
