---

# User data
user_name: danielfm
user_group: danielfm
user_uid: 1000
user_gid: 1000
user_create_ssh_keypair: true
user_extra_home_dirs: []

# Backup
backup_enabled: true
backup_schedule: 'daily'
backup_retention_days: 30
backup_full_period_days: 7
backup_source_dir: '/home/{{ user_name }}'
backup_source_exclude: ''
backup_exclude: ''

# System data
system_timezone: America/Sao_Paulo
system_locale: en_US.UTF-8
system_bluetooth: true
system_dns_over_tls: true
system_dns_dnssec: true
system_resolvconf: |
  nameserver 9.9.9.9
  nameserver 149.112.112.112
