---

dependency:
  name: galaxy

driver:
  name: vagrant

platforms:
  - name: backup-instance-test
    box: archlinux/archlinux
    memory: 512
    cpus: 1

provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
