---

- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Ensure the system package database is up to date
      community.general.pacman:
        update_cache: true
        upgrade: false
