- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - ardour
      - audacity
      - cadence
      - calf
      - carla
      - guitarix
      - jack2
      - lv2-plugins
      - ladspa-plugins
      - dssi-plugins
      - vst-plugins
      - pulseaudio-jack
      - python-dbus
