- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - ardour
      - cadence
      - calf
      - carla
      - guitarix
      - jack2
      - pulseaudio-jack
      - python-dbus

- name: Install realtime kernel patchset
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - linux-rt-lts
