- name: Add security limits file
  become: yes
  copy:
    src: 'etc/security/limits.d/'
    dest: '/etc/security/limits.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Add sysctl files
  become: yes
  copy:
    src: 'etc/sysctl.d/'
    dest: '/etc/sysctl.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'
