- name: Install rxvt-unicode-pixbuf from AUR
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - rxvt-unicode-pixbuf

- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - arandr
      - archlinux-wallpaper
      - cheese
      - chromium
      - dconf-editor
      - deja-dup
      - dunst
      - evince
      - feh
      - file-roller
      - firefox
      - gimp
      - gnome-keyring
      - gnucash
      - gnucash-docs
      - gparted
      - gsimplecal
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - gufw
      - gvfs
      - highlight
      - hsetroot
      - htop
      - i3-gaps
      - libappindicator-gtk2
      - libappindicator-gtk3
      - lightdm
      - lightdm-gtk-greeter
      - lxappearance
      - maim
      - mediainfo
      - mesa-demos
      - mousepad
      - nextcloud-client
      - nitrogen
      - nm-connection-editor
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - otf-ipafont
      - pantheon-calculator
      - papirus-icon-theme
      - pavucontrol
      - pcmanfm
      - polkit-gnome
      - pulseaudio
      - pulseaudio-alsa
      - python-pywal
      - qt5ct
      - ranger
      - rhythmbox
      - rofi
      - seahorse
      - shotwell
      - transmission-gtk
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-fantasque-sans-mono
      - ttf-freefont
      - ttf-indic-otf
      - tumbler
      - urxvt-perls
      - viewnior
      - vlc
      - w3m
      - xfce4-power-manager
      - xorg-apps
      - xorg-xinit

- name: Install packages required for bluetooth support
  become: yes
  pacman:
    state: present
    name:
      - blueman
      - pulseaudio-bluetooth
  when:
    - system_bluetooth|bool

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - i3-scrot
      - light-locker
      - lightdm-settings
      - lightdm-slick-greeter
      - matcha-gtk-theme
      - nerd-fonts-terminus
      - pamac-aur
      - pamac-zsh-completions
      - picom-tryone-git
      - polybar
      - slack-desktop
      - spotify
      - terminess-powerline-font-git
      - timeshift
      - ttf-font-icons
      - ttf-material-design-icons
      - ttf-ms-fonts
      - urxvt-font-size
      - urxvt-resize-font-git
      - xcursor-breeze
