---

- name: Install packages
  become: true
  pacman:
    state: present
    name:
      - arandr
      - archlinux-wallpaper
      - browserpass-chromium
      - browserpass-firefox
      - cheese
      - chromium
      - dunst
      - evince
      - evolution
      - feh
      - file-roller
      - flameshot
      - gcolor3
      - gimp
      - gnome-keyring
      - gparted
      - gsimplecal
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - gufw
      - gvfs
      - highlight
      - hsetroot
      - htop
      - i3-gaps
      - ipp-usb
      - libappindicator-gtk2
      - libappindicator-gtk3
      - libmpdclient
      - lightdm
      - lightdm-gtk-greeter
      - lxappearance
      - mediainfo
      - mesa-demos
      - mopidy
      - mousepad
      - nitrogen
      - nm-connection-editor
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - otf-ipafont
      - pantheon-calculator
      - papirus-icon-theme
      - pavucontrol
      - pcmanfm
      - polkit-gnome
      - pulseaudio
      - pulseaudio-alsa
      - python-pywal
      - qt5ct
      - ranger
      - rhythmbox
      - rofi
      - rxvt-unicode
      - sane
      - sane-airscan
      - seahorse
      - shotwell
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - transmission-gtk
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-fantasque-sans-mono
      - ttf-freefont
      - ttf-indic-otf
      - tumbler
      - urxvt-perls
      - viewnior
      - vlc
      - w3m
      - xfce4-power-manager
      - xorg-apps
      - xorg-xinit
      - xournalpp
      - yubioath-desktop

- name: Install packages required for bluetooth support
  become: true
  pacman:
    state: present
    name:
      - pulseaudio-bluetooth
  when:
    - system_bluetooth|bool

- name: Install AUR packages
  aur:
    name:
      - cava
      - librewolf-bin
      - lightdm-settings
      - lightdm-slick-greeter
      - matcha-gtk-theme
      - mopidy-mpd
      - mopidy-mpris
      - mopidy-spotify
      - nerd-fonts-terminus
      - networkmanager-dmenu-git
      - pamac-aur
      - picom-tryone-git
      - pm-utils
      - polybar
      - slack-desktop
      - terminess-powerline-font-git
      - timeshift
      - ttf-font-icons
      - ttf-material-design-icons
      - ttf-ms-fonts
      - urxvt-font-size
      - urxvt-resize-font-git
      - xcursor-breeze
      - zoom
