- name: Install rxvt-unicode-pixbuf from AUR
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - rxvt-unicode-pixbuf

- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - archlinux-wallpaper
      - dunst
      - file-roller
      - evince
      - gnome-keyring
      - gnucash
      - gnucash-docs
      - gparted
      - gsimplecal
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - gvfs
      - highlight
      - hsetroot
      - htop
      - i3-gaps
      - libappindicator-gtk2
      - libappindicator-gtk3
      - lightdm
      - lightdm-gtk-greeter
      - lxappearance
      - maim
      - mediainfo
      - mesa-demos
      - nitrogen
      - pantheon-calculator
      - papirus-icon-theme
      - polkit-gnome
      - python-pywal
      - qt5ct
      - ranger
      - rhythmbox
      - rofi
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - transmission-gtk
      - tumbler
      - viewnior
      - vlc
      - volumeicon
      - w3m
      - xautolock
      - xfce4-power-manager
      - xorg-apps
      - xorg-xinit
      - urxvt-perls

- name: Install packages required for bluetooth support
  become: yes
  pacman:
    state: present
    name:
      - blueman
  when:
    - system.bluetooth|bool

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - clipit
      - dropbox
      - i3lock-color-git
      - i3-scrot
      - lightdm-settings
      - lightdm-slick-greeter
      - matcha-gtk-theme
      - picom-git
      - polybar
      - slack-desktop
      - spotify
      - ttf-font-icons
      - xcursor-breeze
      - urxvt-font-size
      - urxvt-resize-font-git
      - terminess-powerline-font-git
      - nerd-fonts-terminus
