---

- name: Add system bin scripts
  ansible.builtin.copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755

- name: Change default cursor
  ansible.builtin.lineinfile:
    path: /usr/share/icons/default/index.theme
    regexp: '^Inherits='
    line: Inherits=Breeze

- name: Switch to lightdm-slick-greeter
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^greeter-session='
    line: greeter-session=lightdm-slick-greeter

- name: Run display setup script
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^display-setup-script='
    line: display-setup-script=/usr/bin/xrandr --auto

- name: Hide the user list in lightdm
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^greeter-hide-users='
    line: greeter-hide-users=true

- name: Copy background images
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - usr/share/backgrounds/

- name: Add lightdm-slick-greeter configuration file
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - etc/lightdm/slick-greeter.conf

- name: Ensure the group autologin exists
  ansible.builtin.group:
    name: autologin
    state: present

- name: Enable auto-login in lightdm
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^autologin-user='
    line: 'autologin-user={{ user_name }}'
  when:
    - user_autologin|bool

- name: Disable auto-login in lightdm
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    state: absent
    regexp: '^autologin-user='
  when:
    - not (user_autologin|bool)

- name: Add X11 configuration files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop:
    - etc/X11/xorg.conf.d/

- name: Disable internal speaker beep by default
  ansible.builtin.copy:
    content: blacklist pcspkr
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: 0644

- name: Enable services service
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
  loop:
    - ipp-usb
    - lightdm

- name: Ensure the existence of /usr/bin/i3lock
  ansible.builtin.copy:
    dest: /usr/bin/i3lock
    content: |
      #!/bin/bash
      light-locker-command -l
    owner: root
    group: root
    mode: 0755
