- name: Add system bin scripts
  become: yes
  copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'

- name: Change default cursor
  become: yes
  lineinfile:
    path: /usr/share/icons/default/index.theme
    regexp: '^Inherits='
    line: Inherits=Breeze

- name: Switch to lightdm-slick-greeter
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^greeter-session='
    line: greeter-session=lightdm-slick-greeter

- name: Run display setup script
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^display-setup-script='
    line: display-setup-script=/usr/bin/xrandr --auto

- name: Hide the user list in lightdm
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^greeter-hide-users='
    line: greeter-hide-users=true

- name: Copy background images
  become: yes
  copy:
    src: '{{ item }}'
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: 
    - usr/share/backgrounds/

- name: Add lightdm-slick-greeter configuration file
  become: yes
  copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/lightdm/slick-greeter.conf

- name: Ensure the group autologin exists
  become: yes
  group:
    name: autologin
    state: present

- name: Enable auto-login in lightdm
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^autologin-user='
    line: 'autologin-user={{ user_name }}'
  when:
    - user_autologin|bool

- name: Disable auto-login in lightdm
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    state: absent
    regexp: '^autologin-user='
  when:
    - not (user_autologin|bool)

- name: Add systemd units
  become: yes
  copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/systemd/system/

- name: Add X11 configuration files
  become: yes
  copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/X11/xorg.conf.d/

- name: Disable internal speaker beep by default
  become: yes
  copy:
    content: blacklist pcspkr
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure pulseaudio supports bluetooth
  become: yes
  lineinfile:
    path: /etc/pulse/system.pa
    regexp: '^load-module {{ item }}'
    line: 'load-module {{ item }}'
  loop:
    - module-bluetooth-policy
    - module-bluetooth-discover
  when:
    - system_bluetooth|bool

- name: Load module-echo-cancel PulseAudio module by default
  become: yes
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-echo-cancel'
    line: load-module module-echo-cancel

- name: Enable lightdm service
  become: true
  systemd:
    name: lightdm
    enabled: yes

- name: Enable bluetooth service
  become: yes
  service:
    name: bluetooth
    state: started
    enabled: yes
