- name: Add system bin scripts
  become: yes
  copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'

- name: Change default cursor
  become: yes
  lineinfile:
    path: /usr/share/icons/default/index.theme
    regexp: '^Inherits='
    line: Inherits=Breeze

- name: Switch to lightdm-slick-greeter
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    insertafter: '\[Seat:\*\]'
    regexp: '^greeter-session='
    line: greeter-session=lightdm-slick-greeter

- name: Copy lightdm-slick-greeter background
  become: yes
  copy:
    src: usr/share/backgrounds/lightdm-background.png
    dest: /usr/share/backgrounds/lightdm-background.png
    owner: root
    group: root
    mode: '0644'

- name: Add lightdm-slick-greeter configuration file
  become: yes
  copy:
    src: etc/lightdm/slick-greeter.conf
    dest: /etc/lightdm/slick-greeter.conf
    owner: root
    group: root
    mode: '0644'

- name: Add X11 configuration files
  become: yes
  copy:
    src: etc/X11/xorg.conf.d/
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: '0644'

- name: Disable internal speaker beep by default
  become: yes
  copy:
    content: blacklist pcspkr
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: '0644'

- name: Load module-echo-cancel PulseAudio module by default
  become: yes
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^load-module module-echo-cancel'
    line: load-module module-echo-cancel
