- name: Add user config files
  become: yes
  become_user: '{{ user.name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user.name }}/'
    owner: '{{ user.name }}'
    group: '{{ user.group}}'
    mode: '0644'
  with_items:
    - .Xresources
    - .Xresources.d
    - .gtkrc-2.0
    - .config

- name: Add GTK bookmarks
  become: yes
  become_user: '{{ user.name }}'
  template:
    src: home/.gtk-bookmarks.j2
    dest: '/home/{{ user.name }}/{{ item }}'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0644'
  with_items:
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks

- name: Add user bin scripts
  become: yes
  become_user: '{{ user.name }}'
  copy:
    src: home/.bin/
    dest: '/home/{{ user.name }}/.bin/'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0755'
