- name: Add user config files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .Xresources
    - .Xresources.d
    - .gtkrc-2.0
    - .dmrc
    - .config

- name: Add user to autologin group
  become: yes
  user:
    name: '{{ user_name }}'
    groups:
      - autologin
    append: yes
  when:
    - user_autologin|bool

- name: Add user bin scripts
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.bin/
    dest: '/home/{{ user_name }}/.bin/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Add templated user config files
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks

- name: Add templated system config files
  become: yes
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    mode: '0644'
  loop:
    - etc/udev/rules.d/90-setup-displays.rules

- name: Set DejaDup configuration
  become: yes
  become_user: '{{ user_name }}'
  dconf:
    key: '/org/gnome/deja-dup/{{ item.key }}'
    value: '{{ item.value | string }}'
    state: present
  loop:
    - key: delete-after
      value: 180
    - key: allow-metered
      value: 'false'
    - key: backend
      value: "'google'"
    - key: periodic
      value: 'true'
    - key: periodic-period
      value: 7
    - key: full-backup-period
      value: 30
    - key: google/folder
      value: "'Backups/$HOSTNAME'"
    - key: include-list
      value: ['/home/{{ user_name }}/.chef', '/home/{{ user_name }}/.chef-workstation',
              '/home/{{ user_name }}/.config', '/home/{{ user_name }}/.gnupg',
              '/home/{{ user_name }}/.ssh', '/home/{{ user_name }}/Desktop',
              '/home/{{ user_name }}/Documents', '/home/{{ user_name }}/Music',
              '/home/{{ user_name }}/Pictures', '/home/{{ user_name }}/Projects',
              '/home/{{ user_name }}/Public', '/home/{{ user_name }}/Templates',
              '/home/{{ user_name }}/Videos']
    - key: exclude-list
      value: ['/home/{{ user_name }}/.config/discord', '/home/{{ user_name }}/.config/Slack']
