- name: Add user config files
  become: yes
  become_user: '{{ user.name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user.name }}/'
    owner: '{{ user.name }}'
    group: '{{ user.group}}'
    mode: '0644'
  with_items:
    - .Xresources
    - .Xresources.d
    - .gtkrc-2.0
    - .config

- name: Add user bin scripts
  become: yes
  become_user: '{{ user.name }}'
  copy:
    src: home/.bin/
    dest: '/home/{{ user.name }}/.bin/'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0755'

- name: Ensure the polybar config directory exists
  become: yes
  become_user: '{{ user.name }}'
  file:
    path: '/home/{{ user.name }}/.config/polybar'
    state: directory
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0755'

- name: Add templated user config files
  become: yes
  become_user: '{{ user.name }}'
  template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user.name }}/{{ item }}'
    owner: '{{ user.name }}'
    group: '{{ user.group}}'
    mode: '0644'
  with_items:
    - .config/polybar/config
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks
