- name: Add user config files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .Xresources
    - .Xresources.d
    - .config
    - .dmrc
    - .gtkrc-2.0

- name: Add user-specific application launchers
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/.local/share/applications/'
    dest: '/home/{{ user_name }}/.local/share/applications/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Add user to autologin group
  become: yes
  user:
    name: '{{ user_name }}'
    groups:
      - autologin
    append: yes

- name: Add user bin scripts
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.bin/
    dest: '/home/{{ user_name }}/.bin/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Add templated user config files
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks

- name: Set DejaDup configuration
  become: yes
  become_user: '{{ user_name }}'
  dconf:
    key: '/org/gnome/deja-dup/{{ item.key }}'
    value: '{{ item.value | string }}'
    state: present
  loop:
    - key: allow-metered
      value: 'false'
    - key: periodic
      value: 'true'
    - key: backend
      value: "'{{ backup_backend }}'"
    - key: delete-after
      value: '{{ backup_retention_days }}'
    - key: periodic-period
      value: '{{ backup_period_days }}'
    - key: full-backup-period
      value: '{{ backup_full_period_days }}'
    - key: local/folder
      value: "'{{ backup_local_folder }}'"
    - key: remote/uri
      value: "'{{ backup_remote_storage_uri }}'"
    - key: remote/folder
      value: "'{{ backup_remote_storage_folder }}'"
    - key: google/folder
      value: "'{{ backup_google_folder }}'"
    - key: include-list
      value: '{{ backup_include }}'
    - key: exclude-list
      value: '{{ backup_exclude }}'

- name: Create Firefox profile directory
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: '/home/{{ user_name }}/.mozilla/firefox/default'
    mode: '0755'
    state: directory

- name: Get latest version of ghacks-user.js updater script
  become: yes
  become_user: '{{ user_name }}'
  get_url:
    url: https://github.com/ghacksuserjs/ghacks-user.js/raw/master/updater.sh
    dest: '/home/{{ user_name }}/.mozilla/firefox/default/updater.sh'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Copy user-overrides.js file
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.mozilla/firefox/user-overrides.js
    dest: '/home/{{ user_name }}/.mozilla/firefox/default/user-overrides.js'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Create Firefox profiles.ini file
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.mozilla/firefox/profiles.ini
    dest: '/home/{{ user_name }}/.mozilla/firefox/profiles.ini'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Generate user.js file
  become: yes
  become_user: '{{ user_name }}'
  command:
    chdir: '/home/{{ user_name }}/.mozilla/firefox/default'
    cmd: './updater.sh -s'
