- name: Add user config files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .Xresources
    - .Xresources.d
    - .config
    - .dmrc
    - .gtkrc-2.0

- name: Set duplicity backup exclusion list
  become: yes
  become_user: '{{ user_name }}'
  copy:
    content: '{{ backup_exclude }}'
    dest: '/home/{{ user_name }}/.config/duplicity-backup-exclude'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Add user to autologin group
  become: yes
  user:
    name: '{{ user_name }}'
    groups:
      - autologin
    append: yes

- name: Add user bin scripts
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.bin/
    dest: '/home/{{ user_name }}/.bin/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Write duplicity backup script
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: 'home/.bin/duplicity-backup.sh.j2'
    dest: '/home/{{ user_name }}/.bin/duplicity-backup.sh'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Ensure user systemd directory exists
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: '/home/{{ user_name }}/.config/systemd/user'
    mode: '0755'
    state: directory

- name: Write duplicity systemd unit files
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: 'home/.config/systemd/user/{{ item }}.j2'
    dest: '/home/{{ user_name }}/.config/systemd/user/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - duplicity-backup.service
    - duplicity-backup.timer

- name: Enable duplicity backup timer
  systemd:
    scope: user
    name: duplicity-backup.timer
    state: started
    daemon_reload: true
    enabled: true

- name: Add templated user config files
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks

- name: Create Firefox profile directory
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: '/home/{{ user_name }}/.mozilla/firefox/default'
    mode: '0755'
    state: directory

- name: Get latest version of ghacks-user.js updater script
  become: yes
  become_user: '{{ user_name }}'
  get_url:
    url: https://github.com/ghacksuserjs/ghacks-user.js/raw/master/updater.sh
    dest: '/home/{{ user_name }}/.mozilla/firefox/default/updater.sh'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Copy user-overrides.js file
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.mozilla/firefox/user-overrides.js
    dest: '/home/{{ user_name }}/.mozilla/firefox/default/user-overrides.js'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Create Firefox profiles.ini file
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.mozilla/firefox/profiles.ini
    dest: '/home/{{ user_name }}/.mozilla/firefox/profiles.ini'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Generate user.js file
  become: yes
  become_user: '{{ user_name }}'
  command:
    chdir: '/home/{{ user_name }}/.mozilla/firefox/default'
    cmd: './updater.sh -s'
