---

- name: Ensure config directories exist in $HOME
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    mode: '0755'
    state: directory
  loop:
    - .bin
    - .config
    - .config/gtk-3.0
    - .config/mopidy
    - .config/polybar
    - .librewolf
    - .librewolf/default
    - .librewolf/native-messaging-hosts

- name: Install polybar-themes installer
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/danielfm/polybar-themes.git
    version: fix-rofi
    dest: '/home/{{ user_name }}/.polybar-themes'
    remote: origin
    accept_hostkey: true

- name: Run polybar-themes installer
  become_user: '{{ user_name }}'
  ansible.builtin.shell:
    chdir: '/home/{{ user_name }}/.polybar-themes'
    cmd: 'echo "1" | ./setup.sh'
    creates: '/home/{{ user_name }}/.config/polybar/{{ polybar_base_theme }}'

- name: Create base polybar theme directory
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: '/home/{{ user_name }}/.config/polybar/{{ polybar_base_theme }}/'
    dest: '/home/{{ user_name }}/.config/polybar/active'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'

- name: Add user config files
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .Xresources
    - .Xresources.d
    - .config
    - .dmrc

- name: Add user to autologin group
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups:
      - autologin
    append: true

- name: Add user bin scripts
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: home/.bin/
    dest: '/home/{{ user_name }}/.bin/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Add templated user config files
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gtk-bookmarks
    - .config/gtk-3.0/bookmarks
    - .config/mopidy/mopidy.conf

- name: Set GTK config
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: 'home/{{ item }}.j2'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .gtkrc-2.0
    - .config/gtk-3.0/settings.ini

- name: Download ghacks-user.js updater script
  become_user: '{{ user_name }}'
  ansible.builtin.get_url:
    url: 'https://github.com/ghacksuserjs/ghacks-user.js/raw/{{ userjs_version }}/updater.sh'
    dest: '/home/{{ user_name }}/.librewolf/default/updater.sh'
    checksum: '{{ userjs_checksum }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'

- name: Copy user-overrides.js file
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: home/.librewolf/user-overrides.js
    dest: '/home/{{ user_name }}/.librewolf/default/user-overrides.js'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Create Librewolf profiles.ini file
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: home/.librewolf/profiles.ini
    dest: '/home/{{ user_name }}/.librewolf/profiles.ini'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Generate user.js file
  become_user: '{{ user_name }}'
  ansible.builtin.command:
    chdir: '/home/{{ user_name }}/.librewolf/default'
    cmd: './updater.sh -dsc'
    creates: '/home/{{ user_name }}/.librewolf/default/user.js'

- name: Setup browserpass for librewolf
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    src: '/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json'
    dest: '/home/{{ user_name }}/.librewolf/native-messaging-hosts/com.github.browserpass.native.json'
    state: link
