# User data

user_name: danielfm
user_group: danielfm
user_uid: 1000
user_gid: 1000

user_create_ssh_keypair: yes
user_gnupg_key_id: '0x7105CE6355472DCA'

# Only use this if you have some sort of security mechanism in place
# prior to the login, i.e., disk encryption password prompt
user_autologin: no

# System data

system_timezone: America/Sao_Paulo
system_locale: en_US.UTF-8

system_bluetooth: yes
