---

galaxy_info:
  role_name: i3
  author: Daniel Martins
  description: i3-based window management configuration
  license: BSD
  min_ansible_version: 2.11
  namespace: danielfm
  platforms:
    - name: ArchLinux
      versions:
        - any

collections:
  - kewlfft.aur

dependencies:
  - aur
