- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - browserpass-chromium
      - browserpass-firefox
      - gnupg
      - gopass
      - keybase-gui
      - opensc
      - qrencode
      - tor
      - torbrowser-launcher
      - torsocks
      - yubikey-manager
      - yubikey-personalization-gui
      - yubioath-desktop

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - parcimonie-sh-git
