- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - aws-vault
      - browserpass-chromium
      - browserpass-firefox
      - efitools
      - fwupd
      - gnupg
      - gopass
      - hopenpgp-tools
      - networkmanager-openvpn
      - nmap
      - opensc
      - pam-u2f
      - pinentry
      - qrencode
      - sbsigntools
      - tor
      - torbrowser-launcher
      - torsocks
      - ufw
      - yubikey-manager
      - yubikey-personalization-gui
      - yubikey-touch-detector
      - yubioath-desktop

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - parcimonie-sh-git
      - protonmail-bridge-bin
