---

- name: Install packages
  community.general.pacman:
    state: present
    name:
      - aws-vault
      - efitools
      - fwupd
      - networkmanager-openvpn
      - nmap
      - opensc
      - pam-u2f
      - pinentry
      - qrencode
      - sbsigntools
      - tor
      - torbrowser-launcher
      - torsocks
      - ufw
      - yubikey-manager
      - yubikey-personalization-gui
      - yubikey-touch-detector

- name: Install AUR packages
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - protonmail-bridge-bin
