- name: Set ufw default forward policy
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - parcimonie.sh@all-users
    - pcscd
    - tor
    - ufw

- name: Enable ufw with default incoming deny policy
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Enable ufw with default outgoing allow policy
  become: yes
  ufw:
    state: enabled
    policy: allow
    direction: outgoing

- name: Enable ufw logging
  become: yes
  ufw:
    logging: low

- name: Enable YubiKey support for login and system auth
  become: yes
  lineinfile:
    path: '{{ item }}'
    regex: '^auth .+ pam_yubico.so'
    line: 'auth sufficient pam_yubico.so mode=challenge-response authfile=/etc/yubikey_mappings'
    insertbefore: '^auth .+'
    firstmatch: yes
  loop:
    - /etc/pam.d/login
    - /etc/pam.d/system-auth

- name: Add YubiKey mapping file
  become: yes
  template:
    src: etc/yubikey_mappings.j2
    dest: /etc/yubikey_mappings
    owner: root
    group: root
    mode: '0600'
