- name: Set ufw default forward policy
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - parcimonie.sh@all-users
    - pcscd
    - tor
    - ufw

- name: Enable ufw with default incoming deny policy
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Enable ufw with default outgoing allow policy
  become: yes
  ufw:
    state: enabled
    policy: allow
    direction: outgoing

- name: Enable ufw logging
  become: yes
  ufw:
    logging: low

- name: Enable login 2FA with YubiKey
  become: yes
  lineinfile:
    path: /etc/pam.d/system-local-login
    regex: '^auth .+ pam_u2f.so .+'
    insertafter: '^auth .+'
    line: 'auth required pam_u2f.so authfile=/etc/u2f_mappings nouserok'
  when:
    - (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

# Ref: https://github.com/i3/i3lock/issues/198
- name: i3lock U2F PAM workaround
  become: yes
  file:
    path: /usr/bin/i3lock
    mode: u+s

- name: Enable i3lock 2FA with YubiKey
  become: yes
  lineinfile:
    path: /etc/pam.d/i3lock
    regex: '^auth .+ pam_u2f.so .+'
    insertbefore: '^auth .+'
    line: 'auth required pam_u2f.so authfile=/etc/u2f_mappings nouserok'
  when:
    - (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Enable passwordless sudo with YubiKey
  become: yes
  lineinfile:
    path: /etc/pam.d/sudo
    firstmatch: yes
    insertbefore: '^auth'
    regex: '^auth .+ pam_u2f.so .+'
    line: 'auth sufficient pam_u2f.so authfile=/etc/u2f_mappings'
  when:
    - (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Add U2F key mapping for user
  become: yes
  lineinfile:
    path: /etc/u2f_mappings
    line: '{{ user_name }}:{{ user_pam_u2f_main_key }}:{{ user_pam_u2f_backup_key }}'
    mode: '0400'
    create: yes
  when:
    - (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Disable YubiKey support for system-auth
  become: yes
  lineinfile:
    state: absent
    path: '{{ item }}'
    regex: '^auth .+ pam_u2f.so'
  loop:
    - /etc/pam.d/sudo
    - /etc/pam.d/system-local-login
  when:
    - not (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - not (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Disable i3lock 2FA with YubiKey
  become: yes
  lineinfile:
    state: absent
    regex: '^auth .+ pam_u2f.so .+'
    path: /etc/pam.d/i3lock
  when:
    - not (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - not (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Remove U2F key mapping file for user
  become: yes
  lineinfile:
    state: absent
    regex: '^{{ user_name }}:.+'
    path: /etc/u2f_mappings
  when:
    - not (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - not (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Configure udev to lock screen when YubiKey is removed
  become: yes
  copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - etc/udev/rules.d/90-yubikey.rules
