---

- name: Enable services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - pcscd
    - tor

- name: Enable login 2FA with U2F
  ansible.builtin.lineinfile:
    path: '{{ item }}'
    regex: '^auth .+ pam_u2f.so .+'
    insertafter: '^auth .+'
    line: 'auth required pam_u2f.so authfile=/etc/u2f_mappings nouserok'
  when: user_pam_u2f_key_handles|length > 0
  loop:
    - /etc/pam.d/system-local-login
    - /etc/pam.d/lightdm

- name: Ensure pacman hooks directory exist
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Enable passwordless sudo with U2F
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    firstmatch: true
    insertbefore: '^auth'
    regex: '^auth .+ pam_u2f.so .+'
    line: 'auth sufficient pam_u2f.so authfile=/etc/u2f_mappings'
  when: user_pam_u2f_key_handles|length > 0

- name: Add U2F key mapping for user
  ansible.builtin.lineinfile:
    path: /etc/u2f_mappings
    line: '{{ user_name }}{{ user_pam_u2f_key_handles }}'
    regexp: '^{{ user_name }}.+'
    mode: '0644'
    create: true
  when: user_pam_u2f_key_handles|length > 0

- name: Disable U2F support for system-auth
  ansible.builtin.lineinfile:
    state: absent
    path: '{{ item }}'
    regex: '^auth .+ pam_u2f.so'
  loop:
    - /etc/pam.d/sudo
    - /etc/pam.d/system-local-login
  when: user_pam_u2f_key_handles|length == 0

- name: Remove U2F key mapping file for user
  ansible.builtin.lineinfile:
    state: absent
    regex: '^{{ user_name }}.+'
    path: /etc/u2f_mappings
  when: user_pam_u2f_key_handles|length == 0

- name: Setup OpenVPN client configuration exists
  ansible.builtin.copy:
    src: 'etc/openvpn/client/client.conf'
    dest: '/etc/openvpn/client/client.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
