- name: Set ufw default forward policy
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - parcimonie.sh@all-users
    - pcscd
    - tor
    - ufw

- name: Enable ufw with default incoming deny policy
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Enable ufw with default outgoing allow policy
  become: yes
  ufw:
    state: enabled
    policy: allow
    direction: outgoing

- name: Enable ufw logging
  become: yes
  ufw:
    logging: low

- name: Enable YubiKey support for login and sudo
  become: yes
  lineinfile:
    path: /etc/pam.d/system-auth
    line: 'auth required pam_u2f.so'
  when:
    - (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)

- name: Disable YubiKey support for system-auth
  become: yes
  lineinfile:
    state: absent
    path: /etc/pam.d/system-auth
    regex: '^auth required pam_u2f.so'
  when:
    - not (user_pam_u2f_main_key is defined) and (user_pam_u2f_main_key|length > 0)
    - not (user_pam_u2f_backup_key is defined) and (user_pam_u2f_backup_key|length > 0)
