- name: Ensure the .gnupg directory exists
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: '/home/{{ user_name }}/.gnupg'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0700'

- name: Add GPG configuration file
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: home/.gnupg/gpg.conf.j2
    dest: '/home/{{ user_name }}/.gnupg/gpg.conf'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0600'

- name: Add Dirmngr configuration file
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: home/.gnupg/dirmngr.conf
    dest: '/home/{{ user_name }}/.gnupg/dirmngr.conf'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0600'

- name: Add user configuration files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_aliases.d
    - .bash_env.d
    - .config

- name: Create Gopass config dir
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: '/home/{{ user_name }}/.config/gopass'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0700'

- name: Create Gopass configuration file
  become: yes
  become_user: '{{ user_name }}'
  template:
    src: home/.config/gopass/config.yml.j2
    dest: '/home/{{ user_name }}/.config/gopass/config.yml'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0600'

- name: Enable user services
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    name: '{{ item }}'
    state: started
    scope: user
    enabled: yes
  loop:
    - yubikey-touch-detector
