- name: Update system packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Check if yay AUR helper is available
  stat:
    path: /usr/bin/yay
  register: yay_stat_result

- name: Add AUR dependencies
  become: yes
  pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone yay AUR helper repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  when: yay_stat_result.stat.exists == False

- name: Install yay AUR helper package
  command:
    chdir: /tmp/yay
    cmd: makepkg -si --noconfirm
  when: yay_stat_result.stat.exists == False

- name: Ensure yay AUR helper package is up to date
  aur:
    name:
      - yay
  when: yay_stat_result.stat.exists == True

- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - acpid
      - alsa-lib
      - alsa-plugins
      - alsa-utils
      - avahi
      - base-devel
      - cups
      - curl
      - efitools
      - flatpak
      - foomatic-db-gutenprint-ppds
      - fwupd
      - git
      - git-lfs
      - gutenprint
      - linux-headers
      - man-db
      - man-pages
      - nano
      - neofetch
      - networkmanager
      - networkmanager-openvpn
      - nss-mdns
      - ntfs-3g
      - openssh
      - pavucontrol
      - playerctl
      - realtime-privileges
      - sbsigntools
      - sudo
      - time
      - tree
      - ufw
      - vim
      - wget
      - which
      - xclip
      - xterm
      - zsh

- name: Install packages required for bluetooth support
  become: yes
  pacman:
    state: present
    name:
      - bluez-utils
  when:
    - system.bluetooth|bool

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - pamac-aur
      - ttf-ms-fonts

