---

- name: Ensure the 'aur_builder' user exists
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Ensure the 'aur_builder' user can run 'sudo pacman' without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: Ensure multilib repository is enabled
  community.general.ini_file:
    path: /etc/pacman.conf
    create: false
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Ensure the system package definition is up to date
  community.general.pacman:
    update_cache: true
    upgrade: false

- name: Check if yay AUR helper is available
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_stat_result

- name: Ensure the packages for building AUR packages are installed
  community.general.pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone yay AUR helper repository
  become_user: aur_builder
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    version: master
    dest: /tmp/yay
  when: not yay_stat_result.stat.exists

- name: Install yay AUR helper package
  become_user: aur_builder
  ansible.builtin.command:
    chdir: /tmp/yay
    cmd: makepkg -si --noconfirm
  when: not yay_stat_result.stat.exists

- name: Ensure yay AUR helper package is up to date
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - yay
  when: yay_stat_result.stat.exists

- name: Ensure the desired packages are installed
  community.general.pacman:
    state: present
    name:
      - acpid
      - alsa-lib
      - alsa-plugins
      - alsa-utils
      - avahi
      - base-devel
      - calc
      - cups
      - curl
      - duplicity
      - exfat-utils
      - foomatic-db-gutenprint-ppds
      - git
      - git-lfs
      - gnupg
      - gopass
      - gutenprint
      - iw
      - linux-headers
      - lshw
      - man-db
      - man-pages
      - nano
      - ncdu
      - neofetch
      - networkmanager
      - nss-mdns
      - ntfs-3g
      - ntp
      - openssh
      - playerctl
      - realtime-privileges
      - sudo
      - syncthing
      - time
      - tree
      - vim
      - wget
      - which
      - whois
      - xclip
      - xterm
      - zsh

- name: Ensure the desired AUR packages are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - inxi

- name: Ensure bluetooth packages are installed
  community.general.pacman:
    state: present
    name:
      - blueman
      - bluez-utils
  when:
    - system_bluetooth|bool
