- name: Enable multilib repository
  become: yes
  ini_file:
    path: /etc/pacman.conf
    create: no
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Update system package definition
  become: yes
  pacman:
    update_cache: yes
    upgrade: no

- name: Check if yay AUR helper is available
  stat:
    path: /usr/bin/yay
  register: yay_stat_result

- name: Add AUR dependencies
  become: yes
  pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone yay AUR helper repository
  git:
    repo: https://aur.archlinux.org/yay.git
    version: master
    dest: /tmp/yay
  when: not yay_stat_result.stat.exists

- name: Install yay AUR helper package
  command:
    chdir: /tmp/yay
    cmd: makepkg -si --noconfirm
  when: not yay_stat_result.stat.exists

- name: Ensure yay AUR helper package is up to date
  aur:
    name:
      - yay
  when: yay_stat_result.stat.exists

- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - acpid
      - alsa-lib
      - alsa-plugins
      - alsa-utils
      - avahi
      - base-devel
      - cups
      - curl
      - exfat-utils
      - flatpak
      - foomatic-db-gutenprint-ppds
      - git
      - git-lfs
      - gutenprint
      - linux-headers
      - lshw
      - man-db
      - man-pages
      - nano
      - neofetch
      - networkmanager
      - nss-mdns
      - ntfs-3g
      - ntp
      - openssh
      - playerctl
      - realtime-privileges
      - sudo
      - time
      - tree
      - vim
      - wget
      - which
      - whois
      - xclip
      - xterm
      - zsh
