- name: Update system packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Check if yay AUR helper is available
  stat:
    path: /usr/bin/yay
  register: yay_stat_result

- name: Add AUR dependencies
  become: yes
  pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone yay AUR helper repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  when: yay_stat_result.stat.exists == False

- name: Install yay AUR helper package
  command:
    chdir: /tmp/yay
    cmd: makepkg -si --noconfirm
  when: yay_stat_result.stat.exists == False

- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - acpid
      - alsa-lib
      - alsa-plugins
      - alsa-utils
      - arandr
      - base-devel
      - firefox
      - linux-headers
      - man-db
      - man-pages
      - neofetch
      - network-manager-applet
      - networkmanager
      - networkmanager-openvpn
      - ntfs-3g
      - noto-fonts
      - pavucontrol
      - playerctl
      - pulseaudio
      - pulseaudio-alsa
      - vim
      - which
      - xclip
      - xterm
      - zsh

- name: Install packages required for bluetooth support
  become: yes
  pacman:
    state: present
    name:
      - bluez-utils
      - pulseaudio-bluetooth
  when:
    - system.bluetooth|bool

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - pamac-aur
      - ttf-ms-fonts

