---

- name: Ensure grub configuration is up to date
  ansible.builtin.template:
    src: etc/default/grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify: regenerate grub config

- name: Ensure the correct timezone is set
  community.general.timezone:
    name: '{{ system_timezone }}'

- name: Ensure the correct locale is set
  community.general.locale_gen:
    name: '{{ system_locale }}'

- name: Ensure the maximum size for persistent journal is set
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
    section: Journal
    option: SystemMaxUse
    value: 100M
  notify: restart systemd-journald service

- name: Set up avahi local hostname resolution
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'
  notify: restart avahi-daemon service

- name: Ensure NetworkManager is not allowed to manage resolv.conf
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: 0644
    section: main
    option: rc-manager
    value: unmanaged
  notify: restart NetworkManager service

- name: Ensure the systemd-resolvers configuration directory exists
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure the systemd-resolved configuration is set
  ansible.builtin.template:
    src: etc/systemd/resolved.conf.d/dns_over_tls.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_over_tls.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-resolved service

- name: Ensure the desired system services are enabled and started
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - NetworkManager.service
    - avahi-daemon.service
    - cups.service
    - ntpd.service
    - systemd-resolved.service

- name: Ensure /etc/resolv.conf points to the systemd-resolved stub
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Ensure the user is a member of the lp group
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups: lp
    state: present
    append: true
  when:
    - system_bluetooth|bool

- name: Ensure the bluetooth service is enabled and started
  ansible.builtin.systemd:
    name: bluetooth
    state: started
    enabled: true
  when:
    - system_bluetooth|bool

- name: Ensure the fstrim timer is enabled
  ansible.builtin.systemd:
    name: fstrim.timer
    state: started
    enabled: true
  when:
    - system_has_ssd|bool

- name: Ensure the fstrim timer is disabled
  ansible.builtin.systemd:
    name: fstrim.timer
    state: stopped
    enabled: false
  when:
    - not system_has_ssd|bool

- name: Ensure extra system services are enabled and started
  ansible.builtin.systemd:
    name: '{{ item.name }}'
    state: started
    enabled: true
  loop: '{{ extra_enabled_system_services }}'
  when: extra_enabled_system_services|length > 0
