- name: Set timezone to {{ system_timezone }}
  become: yes
  timezone:
    name: '{{ system_timezone }}'

- name: Ensure the locale {{ system_locale }} exists
  become: yes
  locale_gen:
    name: '{{ system_locale }}'

- name: Set up avahi local hostname resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - NetworkManager
    - avahi-daemon
    - ntpd
    - cups

- name: Install packages required for bluetooth support
  become: yes
  pacman:
    state: present
    name:
      - bluez-utils
  when:
    - system_bluetooth|bool

- name: Disable bluetooth Enhanced Retransmission Mode (ERTM)
  become: yes
  copy:
    src: etc/modprobe.d/xbox_bt.conf
    dest: /etc/modprobe.d/xbox_bt.conf
    owner: root
    group: root
    mode: 0644
  when:
    - system_bluetooth|bool
