- name: Set timezone to {{ system.timezone }}
  become: yes
  timezone:
    name: '{{ system.timezone }}'

- name: Ensure the locale {{ system.locale }} exists
  become: yes
  locale_gen:
    name: '{{ system.locale }}'

- name: Set up avahi local hostname resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Set ufw default forward policy
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - NetworkManager
    - avahi-daemon
    - ntpd
    - org.cups.cupsd
    - ufw

- name: Enable ufw with default incoming deny policy
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Enable ufw with default outgoing allow policy
  become: yes
  ufw:
    state: enabled
    policy: allow
    direction: outgoing

- name: Enable ufw logging
  become: yes
  ufw:
    logging: low
