- name: Set timezone to {{ system_timezone }}
  become: yes
  timezone:
    name: '{{ system_timezone }}'

- name: Ensure the locale {{ system_locale }} exists
  become: yes
  locale_gen:
    name: '{{ system_locale }}'

- name: Set up avahi local hostname resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - NetworkManager
    - avahi-daemon
    - ntpd
    - org.cups.cupsd
