- name: Set timezone to {{ system.timezone }}
  become: yes
  timezone:
    name: '{{ system.timezone }}'

- name: Ensure the locale {{ system.locale }} exists
  become: yes
  locale_gen:
    name: '{{ system.locale }}'

- name: Add /usr/local/bin files
  become: yes
  copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Set up avahi local hostname resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Enable NetworkManager service
  become: yes
  service:
    name: NetworkManager
    state: started
    enabled: yes

- name: Enable avahi service
  become: yes
  service:
    name: avahi-daemon
    state: started
    enabled: yes

- name: Enable org.cups.cupsd service
  become: yes
  service:
    name: org.cups.cupsd
    state: started
    enabled: yes

- name: Ensure pulseaudio supports bluetooth
  become: yes
  lineinfile:
    path: /etc/pulse/system.pa
    regexp: '^load-module {{ item }}'
    line: 'load-module {{ item }}'
  with_items:
    - module-bluetooth-policy
    - module-bluetooth-discover
  when:
    - system.bluetooth|bool

- name: Set ufw default forward policy
  become: yes
  lineinfile:
    path: /etc/default/ufw
    regex: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Enable ufw service
  become: yes
  service:
    name: ufw
    state: started
    enabled: yes
