---

- name: Set timezone to {{ system_timezone }}
  become: true
  timezone:
    name: '{{ system_timezone }}'

- name: Ensure the locale {{ system_locale }} exists
  become: true
  locale_gen:
    name: '{{ system_locale }}'

- name: Set maximum size for persistent journal
  become: true
  ini_file:
    path: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
    section: Journal
    option: SystemMaxUse
    value: 100M
  notify:
    - Restart systemd-resolved

- name: Set up avahi local hostname resolution
  become: true
  lineinfile:
    path: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
    regexp: '^hosts:'
    # yamllint disable-line rule:line-length
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Do not allow NetworkManager to manage resolv.conf
  become: true
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: 0644
    section: main
    option: rc-manager
    value: unmanaged

- name: Set DNS resolvers
  become: true
  copy:
    content: '{{ system_resolvconf }}'
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Create systemd-resolvers conf.d dir
  become: true
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set systemd-resolved configuration
  become: true
  template:
    src: etc/systemd/resolved.conf.d/dns_over_tls.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_over_tls.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart systemd-resolved

- name: Disable bluetooth Enhanced Retransmission Mode (ERTM)
  become: true
  copy:
    src: etc/modprobe.d/xbox_bt.conf
    dest: /etc/modprobe.d/xbox_bt.conf
    owner: root
    group: root
    mode: 0644
  when:
    - system_bluetooth|bool

- name: Enable services
  become: true
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - avahi-daemon
    - NetworkManager
    - ntpd
    - cups
    - systemd-resolved

- name: Enable bluetooth service
  become: true
  service:
    name: bluetooth
    state: started
    enabled: true
  when:
    - system_bluetooth|bool
