---

- name: Ensure {{ user_group }} group exists
  become: true
  ansible.builtin.group:
    name: '{{ user_group }}'
    state: present
    gid: '{{ user_gid }}'

- name: Ensure {{ user_name }} user exists
  become: true
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups:
      - '{{ user_group }}'
      - audio
      - lp
      - network
      - power
      - rfkill
      - sys
      - video
      - wheel
    append: true
    group: '{{ user_group }}'
    uid: '{{ user_uid }}'
    shell: '/bin/zsh'

- name: Ensure the ~/.ssh directory exists for {{ user_name }}
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/.ssh'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0700'

- name: Generate SSH keypair for {{ user_name }}
  become: true
  become_user: '{{ user_name }}'
  community.crypto.openssh_keypair:
    path: '/home/{{ user_name }}/.ssh/id_rsa'
  when:
    - user_create_ssh_keypair|bool

- name: Add extra home directories
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'
  loop: '{{ user_extra_home_dirs }}'

- name: Add home .config directory
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'
  loop:
    - .config
    - .bin

- name: Ensure bash directories exist for {{ user_name }}
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'
  loop:
    - .bash_aliases.d
    - .bash_env.d
    - .bash_completions.d

- name: Add user configuration files
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_logout
    - .bash_profile
    - .bashrc

- name: Set duplicity backup exclusion list
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    content: '{{ backup_exclude }}'
    dest: '/home/{{ user_name }}/.config/duplicity-backup-exclude'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'

- name: Write duplicity backup and restore scripts
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: 'home/.bin/duplicity-{{ item }}.sh.j2'
    dest: '/home/{{ user_name }}/.bin/duplicity-{{ item }}.sh'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0755'
  loop:
    - backup
    - restore

- name: Ensure user systemd directory exists
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/.config/systemd/user'
    mode: '0755'
    state: directory

- name: Write duplicity systemd unit files
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: 'home/.config/systemd/user/{{ item }}.j2'
    dest: '/home/{{ user_name }}/.config/systemd/user/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - duplicity-backup.service
    - duplicity-backup.timer

- name: Enable duplicity backup timer
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.systemd:
    scope: user
    name: duplicity-backup.timer
    state: started
    daemon_reload: true
    enabled: true
  when:
    - backup_enabled

- name: Enable syncthing daemon
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.systemd:
    scope: user
    name: syncthing
    state: started
    enabled: true

- name: Disable duplicity backup timer
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.systemd:
    scope: user
    name: duplicity-backup.timer
    state: stopped
    enabled: false
  when:
    - not backup_enabled
