---

# Whether to enable the Duplicity backup service.
backup_enabled: true

# Systemd schedule for the backup jobs.
backup_schedule: daily

# Accuracy for the Systemd timer.
backup_accuracy: 24h

# Maximum days to keep each backup version.
backup_retention_days: 30

# Force a full backup after that period, and use incremental backups otherwise.
backup_full_period_days: 7

# Main directory to include in the backups.
backup_source_dir: '/home/{{ user_name }}'

# Multi-line string containing file patterns to exclude from the backup.
backup_exclude: ''

# Directory in your `gopass` password store which contains two secrets,
# `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
backup_s3_gopass_secret_dir: duplicity/aws

# Temp directory used by Duplicity. Automatically excluded from the backup.
backup_temp_dir: '/home/{{ user_name }}/.duplicity-tmp'

# GPG key id used to encrypt and sign the Duplicity backups. Will try to
# auto-detect these keys if not provided.
backup_gnupg_signing_key_id: ''
backup_gnupg_encrypt_key_id: ''
