- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - android-tools
      - ansible-lint
      - aspell
      - aspell-en
      - aspell-pt
      - aws-cli
      - bridge-utils
      - dmidecode
      - dnsmasq
      - dnsutils
      - docker
      - docker-compose
      - ebtables
      - emacs
      - gcolor3
      - go
      - jq
      - jdk8-openjdk
      - k9s
      - kubectl
      - libusb-compat
      - maven
      - ovmf
      - openbsd-netcat
      - opensc
      - packer
      - python-pipenv
      - qemu
      - ruby-bundler
      - rubygems
      - smartmontools
      - terraform
      - tmux
      - virt-manager
      - wireshark-qt

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - cfssl
      - chef-dk
      - google-cloud-sdk
      - kail
      - kind-bin
      - pyenv-virtualenv
      - ruby-rubocop
      - zoom
      - zsa-wally
