- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - android-tools
      - aspell
      - aspell-en
      - aspell-pt
      - browserpass-chromium
      - dnsutils
      - docker
      - emacs
      - gnupg
      - go
      - gopass
      - jq
      - k9s
      - keybase-gui
      - kubectl
      - qrencode
      - tmux
      - wireshark-qt
      - yubikey-personalization-gui

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - cfssl
      - chef-dk
      - google-cloud-sdk
      - kail
      - pyenv-virtualenv
      - zoom
      - zsa-wally
