---

- name: Install packages
  become: true
  pacman:
    state: present
    name:
      - android-tools
      - ansible-lint
      - aspell
      - aspell-en
      - aspell-pt
      - bridge-utils
      - dmidecode
      - dnsmasq
      - dnsutils
      - docker-compose
      - emacs
      - go
      - inetutils
      - jq
      - jdk11-openjdk
      - kubectl
      - kubectx
      - leiningen
      - libusb-compat
      - maven
      - net-tools
      - ngrep
      - ovmf
      - openbsd-netcat
      - opensc
      - packer
      - podman
      - podman-docker
      - popeye
      - python-pipenv
      - python-wheel
      - twine
      - ruby-bundler
      - rubygems
      - smartmontools
      - terraform
      - tmux
      - traceroute
      - vagrant
      - vault
      - wireshark-qt
      - yamllint

- name: Install AUR packages
  aur:
    name:
      - aws-cli-v2-bin
      - chef-dk
      - google-cloud-sdk
      - kail
      - kind-bin
      - pip-tools
      - pyenv-virtualenv
      - velero-bin
      - zsa-wally-cli-bin
