- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - android-tools
      - ansible-lint
      - aspell
      - aspell-en
      - aspell-pt
      - bridge-utils
      - dmidecode
      - dnsmasq
      - dnsutils
      - docker
      - docker-compose
      - ebtables
      - emacs
      - go
      - inetutils
      - jq
      - jdk8-openjdk
      - kubectl
      - kubectx
      - leiningen
      - libusb-compat
      - maven
      - net-tools
      - ngrep
      - ovmf
      - openbsd-netcat
      - opensc
      - packer
      - popeye
      - python-pipenv
      - python-wheel
      - twine
      - ruby-bundler
      - rubygems
      - smartmontools
      - terraform
      - tmux
      - traceroute
      - vagrant
      - vault
      - wireshark-qt

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - aws-cli-v2-bin
      - chef-dk
      - google-cloud-sdk
      - kail
      - kind-bin
      - ngrok-bin
      - pip-tools
      - pyenv-virtualenv
      - velero-bin
      - zsa-wally-cli-bin
