- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - android-tools
      - aspell
      - aspell-en
      - aspell-pt
      - browserpass-chromium
      - dnsutils
      - docker
      - emacs
      - gnupg
      - go
      - gopass
      - jq
      - k9s
      - keybase-gui
      - kubectl
      - libusb-compat
      - opensc
      - qrencode
      - ruby-bundler
      - rubygems
      - tmux
      - tor
      - torbrowser-launcher
      - torsocks
      - virtualbox-host-dkms
      - virtualbox-guest-iso
      - wireshark-qt
      - yubikey-manager
      - yubikey-personalization-gui
      - yubioath-desktop

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - cfssl
      - chef-dk
      - google-cloud-sdk
      - kail
      - parcimonie-sh-git
      - pyenv-virtualenv
      - zoom
      - virtualbox-ext-oracle
      - zsa-wally
