- name: Install packages
  become: yes
  pacman:
    state: present
    name:
      - android-tools
      - aspell
      - aspell-en
      - aspell-pt
      - dnsutils
      - docker
      - emacs
      - go
      - jq
      - k9s
      - kubectl
      - libusb-compat
      - opensc
      - ruby-bundler
      - rubygems
      - tmux
      - virtualbox-host-dkms
      - virtualbox-guest-iso
      - wireshark-qt

- name: Install AUR packages
  aur:
    upgrade: no
    skip_installed: yes
    name:
      - cfssl
      - chef-dk
      - google-cloud-sdk
      - kail
      - pyenv-virtualenv
      - zoom
      - virtualbox-ext-oracle
      - zsa-wally
