---

- name: Ensure subuid settings are set
  ansible.builtin.copy:
    content: '{{ user_name }}:100000:65537'
    dest: /etc/subuid
    owner: root
    group: root
    mode: 0644

- name: Ensure subgid settings are set
  ansible.builtin.copy:
    content: '{{ user_group }}:100000:65537'
    dest: /etc/subgid
    owner: root
    group: root
    mode: 0644
