- name: Ensure Docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - docker
    - pcscd
    - tor
