- name: Ensure groups exist
  become: yes
  group:
    name: '{{ item }}'
    state: present
  loop:
    - docker
    - libvirt

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - docker
    - iptables
