- name: Ensure Docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Enable the Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Enable the pcscd service
  become: yes
  service:
    name: pcscd
    state: started
    enabled: yes
