---

- name: Add user configuration files
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_aliases.d
    - .bash_completions.d
    - .bash_env.d
    - .gitignore_global
    - .nanorc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Add user configuration templates
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: home/{{ item }}.j2
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_env.d/11-emacs.sh
    - .gitconfig

- name: Install oh-my-zsh
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    version: master
    dest: '/home/{{ user_name }}/.oh-my-zsh'
    remote: readonly
    accept_hostkey: true

- name: Install tmux plugin manager
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    version: master
    dest: '/home/{{ user_name }}/.tmux/plugins/tpm'
    remote: readonly
    accept_hostkey: true

- name: Install vundle plugin manager
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    version: master
    dest: '/home/{{ user_name }}/.vim/bundle/vundle'
    remote: readonly
    accept_hostkey: true

- name: Install emacs configuration
  become: true
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/danielfm/dotfiles-emacs.git
    version: master
    dest: '/home/{{ user_name }}/.emacs.d'
    remote: readonly
    accept_hostkey: true
