---

- name: Ensure user is in the desired group
  ansible.builtin.user:
    name: '{{ user_name }}'
    append: true
    groups:
      - docker

- name: Ensure user configuration files exist
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_aliases.d
    - .bash_completions.d
    - .bash_env.d
    - .gitignore_global
    - .nanorc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Ensure templated user configuration files exist
  become_user: '{{ user_name }}'
  ansible.builtin.template:
    src: home/{{ item }}.j2
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
    mode: '0644'
  loop:
    - .bash_env.d/11-emacs.sh
    - .gitconfig

- name: Ensure oh-my-zsh is installed
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    version: master
    dest: '/home/{{ user_name }}/.oh-my-zsh'
    remote: readonly
    accept_hostkey: true

- name: Ensure tmux plugin manager is installed
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    version: master
    dest: '/home/{{ user_name }}/.tmux/plugins/tpm'
    remote: readonly
    accept_hostkey: true

- name: Ensure vundle plugin manager is installed
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    version: master
    dest: '/home/{{ user_name }}/.vim/bundle/vundle'
    remote: readonly
    accept_hostkey: true

- name: Ensure my personal emacs configuration is installed
  become_user: '{{ user_name }}'
  ansible.builtin.git:
    repo: https://github.com/danielfm/dotfiles-emacs.git
    version: master
    dest: '/home/{{ user_name }}/.emacs.d'
    remote: readonly
    accept_hostkey: true
