- name: Add user configuration files
  become: yes
  become_user: '{{ user.name }}'
  copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user.name }}/'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0644'
  loop:
    - .bash_aliases.d
    - .bash_completions.d
    - .bash_env.d
    - .gitignore_global
    - .nanorc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Add user configuration templates
  become: yes
  become_user: '{{ user.name }}'
  template:
    src: home/{{ item }}.j2
    dest: '/home/{{ user.name }}/{{ item }}'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0644'
  loop:
    - .bash_env.d/11-emacs.sh
    - .gitconfig

- name: Ensure {{ user.name }} is in the required groups
  become: yes
  user:
    name: '{{ user.name }}'
    groups:
      - docker
      - libvirt
      - vboxusers
    append: yes

- name: Add extra directories
  become: yes
  become_user: '{{ user.name }}'
  file:
    path: '/home/{{ user.name }}/{{ item }}'
    state: directory
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: '0755'
  loop:
    - Projects

- name: Install oh-my-zsh
  become: yes
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '/home/{{ user.name }}/.oh-my-zsh'
    remote: readonly
    accept_hostkey: yes

- name: Install tmux plugin manager
  become: yes
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '/home/{{ user.name }}/.tmux/plugins/tpm'
    remote: readonly
    accept_hostkey: yes

- name: Install vundle plugin manager
  become: yes
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: '/home/{{ user.name }}/.vim/bundle/vundle'
    remote: readonly
    accept_hostkey: yes

- name: Install emacs configuration
  become: yes
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/danielfm/dotfiles-emacs.git
    dest: '/home/{{ user.name }}/.emacs.d'
    remote: readonly
    accept_hostkey: yes
