---

# GnuPG keyserver address.
user_gnupg_keyserver: hkp://pool.sks-keyservers.net

# 2FA support with a U2F security key (i.e. YubiKey)
# Format: ':<key-handle>,<public-key>:<key-handle-2>,<public-key-2>:...'
user_pam_u2f_key_handles: ''

# Location to store the generate secure boot keys.
system_secure_boot_keys_dir: /root/.secure-boot-keys
